Initial Commit
im-open/iis-site-create pull request #1
Opened 2021-08-17 15:33 UTC by hpractv

2021-08-18 13:22 UTC, danielle-casella-adams requested changes
Have you been able to test this out?

2021-08-18 13:22 UTC, danielle-casella-adams commented on README.md
> +The IIS site create action uses Web Services for Management, [WSMan], and Windows Remote Management, [WinRM], to create remote administrative sessions. Because of this, Windows OS GitHubs Actions Run
```suggestion
The IIS site create action uses Web Services for Management, [WSMan], and Windows Remote Management, [WinRM], to create remote administrative sessions. Because of this, Windows Actions Runners, `runs-on: [windows-2019]`, must be used. If the IIS server target is on a local network that is not publicly available, then specialized self-hosted runners, `runs-on: [self-hosted, windows-2019]`,  will need to be used to broker commands to the server.
```

2021-08-18 13:22 UTC, danielle-casella-adams commented on README.md
> +  stop-iis:
```suggestion
create-iis-site:
```

2021-08-18 13:22 UTC, danielle-casella-adams commented on README.md
> +          server: '${{ secrets.iis_server }}'
```suggestion
          server: '${{ env.server }}'
```

2021-08-18 13:22 UTC, danielle-casella-adams commented on README.md
> +          server-public-key: ${{ env.IIS_SERVER_CERT_PATH}}
The ones that are using envs should be added to the section above.  And the envs above should be updated to reflect what's being used here like for the cert path and app pool name.

2021-08-25 18:02 UTC, hpractv commented on README.md
> +  stop-iis:
👍🏽

2021-08-25 18:02 UTC, hpractv commented on README.md
> +The IIS site create action uses Web Services for Management, [WSMan], and Windows Remote Management, [WinRM], to create remote administrative sessions. Because of this, Windows OS GitHubs Actions Run
👍🏽

2021-08-25 18:03 UTC, hpractv commented on README.md
> +          server: '${{ secrets.iis_server }}'
👍🏽

2021-08-25 20:14 UTC, hpractv commented
> Have you been able to test this out?

Yes tested with a Win IIS Server in the GitHub Resources Group

2021-08-30 16:00 UTC, danielle-casella-adams approved these changes

2021-08-31 22:14 UTC, merged